# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Publish

on:
  release:
    types: [created]

defaults:
  run:
    working-directory: packages/react-native-jigsaw

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Restore node_modules cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit`
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typescript

      - name: Build
        run: yarn build

      - name: Publish to npm registry
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
